slam_toolbox:
  ros__parameters:
    use_sim_time: false
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan
    mode: mapping

    resolution: 0.05
    max_laser_range: 8.0
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.1
    map_update_interval: 5.0

    transform_publish_period: 0.05
    use_scan_matching: true
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1

    loop_closure_threshold: 0.8
    loop_closure_search_radius: 5.0
    do_loop_closing: true
    use_pose_graph: true
